name: TradeShop
version: 0.0.1
description: Plugin that allows players to create a trade based shop.
authors: [Alshain01, TheSabreSlicer]
#website: http://
main: alshain01.TradeShop.TradeShop
softdepend: [Flags]
commands:
  tradeshop:
    description: Allows you to perform actions on TradeShops.
    permission: tradeshop.user
    usage: /tradeshop <create|add|delete>
    alisases: ts
permissions:
  tradeshop.user:
    description: Gives access to create a TradeShop.
    default: true
  tradeshop.admin:
    description: Allows a user to view and destroy any TradeShop chest, regardless of owner.
    default: op
